# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "Quantic Warp"

# A description of your site for social meta tag, search engines, and feed.xml
description: "Game studio."


# The subpath of your site, e.g. /blog, for generating urls
baseurl:

sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "https://quanticwarp.github.io/"

# The shortname for your Disqus site to enable comments.
disqus:

# Author information - author info at the bottom of the post
author_name: "John Choque"

# Social links in the site footer
twitter_username: "quanticwarp"
facebook_username: "quanticwarp"
instagram_username: "quanticwarp"

collections:
  games:
    output: true
    permalink: /games/:name
  press:
    output: true
    permalink: /press/:name
